# Generated by Django 6.0 on 2026-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artworkimage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artworkimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('artwork',), name='unique_primary_image_per_artwork'),
        ),
    ]
