# Generated by Django 6.0 on 2026-01-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artworkimage_unique_primary_image_per_artwork'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artworkimage',
            name='unique_primary_image_per_artwork',
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
