# Generated by Django 6.0 on 2026-01-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_remove_artworkimage_unique_primary_image_per_artwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='edition_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='edition_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_unique',
            field=models.BooleanField(default=True),
        ),
    ]
