# Generated by Django 6.0 on 2026-01-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
